version: "3"

services:
  translation-api:
    build: .
    ports:
      - "3000-3003:3000-3003"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./.env:/usr/src/app/.env
    restart: unless-stopped
